// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CreateActivityInput struct {
	Type     string `json:"type"`
	Date     string `json:"date"`
	Duration int    `json:"duration"`
}

type Mutation struct {
}

type Query struct {
}
