package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"activity/internal/auth"
	"activity/internal/models"
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// Date is the resolver for the date field.
func (r *activityResolver) Date(ctx context.Context, obj *models.Activity) (string, error) {
	return obj.Date.Format("2006-01-02"), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *activityResolver) CreatedAt(ctx context.Context, obj *models.Activity) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// CreateActivity is the resolver for the createActivity field.
func (r *mutationResolver) CreateActivity(ctx context.Context, input CreateActivityInput) (*models.Activity, error) {
	userIDValue := ctx.Value(auth.UserIDKey)
	if userIDValue == nil {
		return nil, errors.New("user not authenticated")
	}

	userID, ok := userIDValue.(string)
	if !ok {
		return nil, errors.New("invalid user context")
	}

	date, err := time.Parse("2006-01-02", input.Date)
	if err != nil {
		return nil, err
	}

	activity := &models.Activity{
		ID:        uuid.New().String(),
		UserID:    userID,
		Type:      input.Type,
		Date:      date,
		Duration:  input.Duration,
		CreatedAt: time.Now(),
	}

	if err := r.DB.Create(activity).Error; err != nil {
		return nil, err
	}

	return activity, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	userIDValue := ctx.Value(auth.UserIDKey)
	if userIDValue == nil {
		return nil, errors.New("user not authenticated")
	}

	userID, ok := userIDValue.(string)
	if !ok {
		return nil, errors.New("invalid user context")
	}

	var user models.User
	if err := r.DB.Preload("Activities").First(&user, "id = ?", userID).Error; err != nil {
		return nil, err
	}

	return &user, nil
}

// Activities is the resolver for the activities field.
func (r *queryResolver) Activities(ctx context.Context, userID string) ([]*models.Activity, error) {
	var activities []*models.Activity
	if err := r.DB.Where("user_id = ?", userID).Find(&activities).Error; err != nil {
		return nil, err
	}

	return activities, nil
}

// Activity returns ActivityResolver implementation.
func (r *Resolver) Activity() ActivityResolver { return &activityResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type activityResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *activityResolver) ID(ctx context.Context, obj *models.Activity) (string, error) {
	return obj.ID, nil
}
